name: Docker Image CI

on:
  push:
    branches:
      - "main"  # You can specify any branch here
  pull_request:
    branches:
      - "main"  # This triggers the workflow on PRs to the 'main' branch

jobs:
  build-and-push:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to AWS ECR
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        INFRA_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        docker login -u AWS -p $(aws ecr get-login-password --region "$AWS_REGION") "$INFRA_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com"


    - name: Tag Docker image for ECR
      env:
        AWS_REGION: ap-south-1
        INFRA_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_ID }}
      run: docker tag alphaprasad01/cicddemo:latest $INFRA_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo:latest

    - name: Push Docker image to AWS ECR
      env:
        AWS_REGION: ap-south-1
        INFRA_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_ID }}
      run: docker push $INFRA_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo:latest
