name: Docker Image CI

on:
  push:
    branches:
      - "main"  # You can specify any branch here
  pull_request:
    branches:
      - "main"  # This triggers the workflow on PRs to the 'main' branch

jobs:
  build-and-push:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug Secrets
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        INFRA_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "AWS Region: $AWS_REGION"
        echo "Account Number: $INFRA_ACCOUNT_NUMBER"
        echo "Access Key ID: ${AWS_ACCESS_KEY_ID:0:4}****" # Masked for security
        echo "Secret Access Key: ${AWS_SECRET_ACCESS_KEY:0:4}****"
        echo "Docker Username: $DOCKER_USERNAME"

      
    - name: Log in to AWS ECR
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        INFRA_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$INFRA_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com"


    - name: Tag Docker image for ECR
      env:
        AWS_REGION: ap-south-1
        INFRA_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_ID }}
      run: docker tag alphaprasad01/cicddemo:latest $INFRA_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo:latest

    - name: Push Docker image to AWS ECR
      env:
        AWS_REGION: ap-south-1
        INFRA_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_ID }}
      run: docker push $INFRA_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/cicddemo:latest
