name: Docker Image CI

on:
  push:
    branches:
      - "main"  # You can specify any branch here
  pull_request:
    branches:
      - "main"  # This triggers the workflow on PRs to the 'main' branch

jobs:
  build-and-push:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
   # Log in to AWS ECR using aws-actions/amazon-ecr-login v2
    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    # Tag the Docker image for AWS ECR
    - name: Tag Docker image for ECR
      run: docker tag alphaprasad01/cicddemo:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/cicddemo:latest

    # Push the Docker image to AWS ECR
    - name: Push Docker image to AWS ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/cicddemo:latest
